SCREEN_WIDTH = 1500
SCREEN_HEIGHT = 600
BACKGROUND_VELOCITY = -300
PLAYER_WIDTH = 130
PLAYER_HEIGHT = 50
BUILDING_HEIGHT = 100
BUILDING_WIDTH = 600
BUILDING_RATIO = 0.47
POLICECAR_WIDTH = 160
POLICECAR_HEIGHT = 70
POLICECAR_VELOCITY = 200
WARN_WIDTH = 50
WARN_HEIGHT = 10
BULLET_WIDTH = 50
BULLET_HEIGHT = 50
SHOOT_COOLDOWN = 2  # second
# BULLET_SPEED = -BACKGROUND_VELOCITY
QUICKFIRE_SKILL_COOLDOWN = 10  # second
QUICKFIRE_COOLDOWN = 0.15  # second
OBSTACLE_WIDTH = 30
OBSTACLE_HEIGHT = 90
OBSTACLE_COOLDOWN = 2  # second
EXPLODE_HEIGHT = 180
EXPLODE_WIDTH = 100

PLAYER_ACC = 20
FRICTION_HORI = PLAYER_ACC * 0.4
FRICTION_VERT = PLAYER_ACC * 0.6
PLAYER_MAX_HORI_SPEED = 2 * -BACKGROUND_VELOCITY

# debug
DISABLE_BUILDINGS = False
SHOW_FPS = False
